name: Countdown
options:
  bundleIdPrefix: nl.stokerconsulting
  deploymentTarget:
    iOS: "17.0"
targets:
  Countdown:
    type: application
    platform: iOS
    sources: [Countdown]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: nl.stokerconsulting.countdown
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_CFBundleDisplayName: Countdown
        INFOPLIST_KEY_UIUserInterfaceStyle: Dark
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: "5.9"
